### ISSUE TITLE
fits clobber has been deprecated

### ISSUE THREAD

**Issue by mcara** [spacetelescope/stsci.tools#19]
The ``clobber`` parameter in ``astropy.io.fits`` write functions has been deprecated and it has been replaced with ``overwrite``: see https://github.com/astropy/astropy/pull/5171.

This has caused our code (see, e.g., ``drizzlepac`` - https://github.com/spacetelescope/drizzlepac/issues/15) to issue numerous deprecation warnings.

The code in ``stsci.tools`` needs to be updated so that it uses ``overwrite`` for versions of astropy  >= 1.3 and ``clobber`` for verions < 1.3 (for backward compatibility).

**Comment by pllim** [comment]
Fixed in #20.
