### ISSUE TITLE
matplotlib and TEAL

### ISSUE THREAD

**Issue by rjavila** [spacetelescope/stsci.tools#2]
I ran into problems using matplotlib and TEAL. It seems they each use a different default backends so when I load one of the two packages the other won't work.

**Comment by pllim** [comment]
You can always change your matplotlib backend (see http://matplotlib.org/faq/usage_faq.html#what-is-a-backend). If that does not work, post your backend settings for each and the related tracebacks.

**Comment by rjavila** [comment]
Well, shouldn't the backends match by default? Otherwise anyone who downloads these two package will run into problems when they use Drizzlepac. That's how I ran into it.

**Comment by pllim** [comment]
matplotlib and TEAL are two very different beasts. They are developed by different people. And they don't really talk to each other in terms of matching backend. Have them automatically attempt to match is not going to be feasible. But, maybe there is a way for TEAL to check currently active matplotlib backend and issue a warning? I am not sure. What do you think, @cdsontag ?

**Comment by rjavila** [comment]
My personal workaround is to set the backend to TkAgg in my matplotlibrc file.

**Comment by pllim** [comment]
@rjavila , @cdsontag said, "Easiest way to get them to work together (I think) is to just use TkAgg for both."
