### ISSUE TITLE
numpy.diagonal returns a read-only array

### ISSUE THREAD

**Issue by philhodge** [spacetelescope/stsci.tools#4]
A user reported an exception when using the `mktrace` module in `stistools`.  The problem is in function `qrsolv` in `stsci.tools.nmpfit.py`:

``` python
    numpy.put(x, ipvt, wa)
```

where `x` is the diagonal of another array:

``` python
    x = numpy.diagonal(r)
```

The `numpy.put` function was called to replace some elements of `x` with the values of `wa`, at indices specified by `ipvt`.  In some versions of `numpy`, however, `diagonal()` returns a read-only array.  For example:

``` python
    >>> print("{}".format(np.__version__))
    1.10.4
    >>> x = np.arange(5 * 5, dtype=np.float64).reshape((5, 5))
    >>> d = np.diagonal(x)
    >>> d[1] = 37.
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ValueError: assignment destination is read-only
```

EDIT: Also see FootPrints Issue 8421.

**Comment by pllim** [comment]
@philhodge , are you or @stscirij going to work on this?

**Comment by pllim** [comment]
@larrybradley , are you aware of anything in Astropy or `photutils` or such that can replace https://github.com/spacetelescope/stsci.tools/blob/master/lib/stsci/tools/nmpfit.py ?

**Comment by stscirij** [comment]
I'll do this.

On Jul 7, 2016 11:13 AM, "P. L. Lim" <notifications@github.com> wrote:

@philhodge<https://github.com/philhodge> , are you or @stscirij<https://github.com/stscirij> going to work on this?

**Comment by philhodge** [comment]
The gfit1d function in gfit.py is the one that calls nmpfit.

Phil

**Comment by nden** [comment]
`nmpfit` should be replaced by `astropy.modeling.fitting.LevMarLSQFitter`.

**Comment by larrybradley** [comment]
@pllim Yes, `LevMarLSQFitter` as @nden suggests.

**Comment by mcara** [comment]
@philhodge A simple fix (instead of re-writting the whole module) is to make diagonal read-write:

```python
>>> import numpy as np
>>> x = np.arange(5 * 5, dtype=np.float64).reshape((5, 5))
>>> d = np.diagonal(x)
>>> d[1] = 37.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: assignment destination is read-only
>>> d = np.array(np.diagonal(x))
>>> d[1] = 37.
>>> 
```
If this solution is acceptable, I can make a quick PR.

**Comment by philhodge** [comment]
I doubt that that would work.  I don't remember the code, but I think 
the intention is to change the matrix by modifying the diagonal.

**Comment by mcara** [comment]
@philhodge Based on the numpy documentation for ``diagonal``:

> In versions of NumPy prior to 1.7, this function always returned a new, independent array containing a copy of the values in the diagonal.

> In NumPy 1.7 and 1.8, it continues to return a copy of the diagonal, but depending on this fact is deprecated. Writing to the resulting array continues to work as it used to, but a FutureWarning is issued.

> Starting in NumPy 1.9 it returns a read-only view on the original array. Attempting to write to the resulting array will produce an error.

> **In some future release, it will return a read/write view and writing to the returned array will alter your original array.** The returned array will have the same type as the input array.

> If you don’t write to the array returned by this function, then you can just ignore all of the above.

> **If you depend on the current behavior, then we suggest copying the returned array explicitly, i.e., use np.diagonal(a).copy() instead of just np.diagonal(a). This will work with both past and future versions of NumPy.**

Also, please note, _"In some future release, it will return a read/write view and writing to the returned array will alter your original array."_ However, I am not aware that this functionality was ever supported in the past and so, I do not see how existing code could have relied on such functionality.

**Comment by philhodge** [comment]
Then your solution should work. Thanks!

Phil

**Comment by jotaylor** [comment]
I did a quick (not very rigorous) check to test the proposed fix, and I seem to be getting the same error. I'm not on the STIS team anymore but am passing this information on to them for further testing.

**Comment by mcara** [comment]
@jotaylor Most likely your installation does not contain this fix. If it does, could you, please, put some test files and exact commands that need to be run to reproduce the error somewhere for download?

**Comment by jotaylor** [comment]
@mcara Yup, you're right Mihai, my installation didn't have the fix. I manually edited the offending line in nmpfit.py to duplicate your change and got mktrace to run correctly 👍  Do you know how long it will take to get incorporated into the public astroconda distribution?

**Comment by pllim** [comment]
@jotaylor , as soon as someone makes a GitHub release tag and update `astroconda-contrib`.

**Comment by pllim** [comment]
But maybe we should merge #9 before making a release?

**Comment by mcara** [comment]
It depends on when @stscirij is going to add release tag [or whatever is the correct wording for this] to the ``stsci.tools`` package.

**Comment by stscirij** [comment]
Regardless, it will go in the next release when I figure out how to make that happen.

**Comment by jhunkeler** [comment]
I agree with @pllim. #9 should be merged (assuming it is ready to go).

**Comment by pllim** [comment]
Release 3.4.4 is made, closing this call.
