### ISSUE TITLE
pytools/utils/cfgobj test failed in Python 3

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci.tools#41]
I think it is a test for this package?

https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=106067037

**Comment by cdsontag** [comment]
Yes it is.  If someone (myself later is possible) could verify that the diffs are simply whitespace, then we could OKify (just accept the new output).

**Comment by pllim** [comment]
@cdsontag , are you also fixing this in conjuction with spacetelescope/pyraf#36 😄

**Comment by cdsontag** [comment]
Was going to handle this one separately after I fix the PyRAF tests.

**Comment by cdsontag** [comment]
The cfgobj tests on Python3 are good now and passing today.  Closing this.  But @pllim feel free to re-open if you have further concerns.

**Comment by pllim** [comment]
Thanks, Chris! 🎉
