### ISSUE TITLE
Documentation should be moved to RTD

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci.tools#42]
`stsci.tools` documentation is no longer being actively built after transition to GitHub. The documentation should:

1. be moved to ReadTheDocs and tied to this repo
2. updated to be more user-friendly; for example, someone asked about the ASN tools in this package but I needed to create a custom Gist (https://gist.github.com/pllim/86954c6783eb2bb9c3b552edbdd134a7) instead of just pointing to the doc here.

c/c @SaraOgaz

**Comment by pllim** [comment]
UPDATE: http://ssb.stsci.edu/doc/stsci_python_dev/stsci.tools.doc/html/index.html is no longer accessible. So, `stsci.tools` now does not have any accessible user documentation.

**Comment by jhunkeler** [comment]
Same thing for this:
https://github.com/spacetelescope/stsci.tools/blob/df5696d7b7f63867d31288401c19240688bea8aa/scripts/stscidocs#L10

@mcara Can `stscidocs` be retired? The documentation set(s) it used to point to were last updated in 2011 anyway.

**Comment by mcara** [comment]
@jhunkeler I do not see what purpose `scidocs` does serve... 😕

**Comment by pllim** [comment]
You can remove that. We haven't used `epydoc` in many years.
