### ISSUE TITLE
Please upload a current version to pypi

### ISSUE THREAD

**Issue by olebole** [spacetelescope/stsci.tools#51]
The version currently on Pypi is quite old and does not support recent astropy versions. The versions on github seem to be more recent.

Would it possible to put the newest version to pypi as well? I would like to use pypi as the source for the Debian package.

**Comment by pllim** [comment]
@olebole , any chance you could grab the latest release for this package from our `astroconda` channel (http://astroconda.readthedocs.io/en/latest/) instead? 

According to https://pypi.python.org/pypi/stsci.tools/3.4.3 , `stsci_ssb` (@stsci-hack is this your account?) and @cdsontag are the owners. If possible, ownership should be given to @jhunkeler and @rendinam as well. One of the owners can then upload 3.4.5 to PyPI.

**Comment by olebole** [comment]
Since I need (just) the source, I downloaded from github, and may continue to do so if the pypi upload has difficulties for you.

**Comment by rendinam** [comment]
`stsci.tools 3.4.11` is now available on PyPI.
