### ISSUE TITLE
Release 3.4.12

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci.tools#63]
It's all yours, Mihai.

**Comment by jhunkeler** [comment]
@pllim @mcara 
Is this release blocked or anything? Can I just do it now?

🎅

**Comment by pllim** [comment]
I was hoping to look into a better way to fix lazy loading bug for `stpyfits` but that should not hold up the release. So :rocket: away!

**Comment by mcara** [comment]
Oh, ... Well, I think you can go ahead and make a release. I hope it can get into 2018.1 ? Also, I was hoping I could fix some things but it does not look like I can do it fast enough. So, go ahead and make a release.

**Comment by pllim** [comment]
Can you please push the release to PyPI too?

**Comment by jhunkeler** [comment]
Sure thing
🎅

**Comment by jhunkeler** [comment]
Done
https://pypi.python.org/pypi/stsci.tools/3.4.12
