### ISSUE TITLE
Get rid of defunct tester tools

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci.tools#73]
I want to delete these from the repo. Any objections?

* lib/stsci/tools/tester.py
* lib/stsci/tools/testutil.py

**Comment by mcara** [comment]
Is there anything that uses them? If not - 👍

**Comment by pllim** [comment]
> Is there anything that uses them?

I don't know. Does drizzlepac use them?

**Comment by mcara** [comment]
It does not look like it uses it. What about other packages or our regression tests?

**Comment by pllim** [comment]
Not any of mine. Let's see what others say.

**Comment by nden** [comment]
`grep` on those two files in a conda-dev installation does not show anything. 
:+1: on removing them.

**Comment by nden** [comment]
`numerixenv` needs to be removed too. It was written many years ago to check if a user had numarray or numpy installed on their system. It needs to be removed also from all other modules in stsci.tools.

**Comment by pllim** [comment]
Talking about `numarray`, it also needs to be cleaned from `versioninfo.py`.

Also, xref #74 for a mysterious `stash.py`.
